# important features for the pictures
dataset: food
attributes: food
cluster_feature_method: linear # [kmeans, random, linear]
model_type: clip
model_size: ViT-B/32
mahalanobis: false
division_power: 2
linear_epochs: 200
reinit: true # True/False
num_attributes: 101 # [16, 32, 64, 128, 256, 512]
seed: 0

# optimization parameters
lr: 0.01
batch_size: 4096
epochs: 2000

# model structure
linear_model: [linear, bn, linear] 
score_model: [bn, linear]