# important features for the pictures
dataset: imagenet-animal
attributes: imagenet-animal
cluster_feature_method: linear # [kmeans, random, linear]
model_type: clip
model_size: ViT-B/32
mahalanobis: true
division_power: 2
linear_epochs: 500
reinit: true # True/False
num_attributes: 4 # [16, 32, 64, 128, 256, 512]
seed: 0

# optimization parameters
lr: 0.01
batch_size: 32768
epochs: 1000

# model structure
linear_model: [linear, bn, linear] 
score_model: [bn, linear] 
